config/routes.rb
 Rails.application.routes.draw do
  root 'home#index'

  get '/home', to: 'home#index', as: :home_root
  get 'index', to: 'home#index'
  get 'home/meinkonto', to: 'home#meinkonto'
  get 'home/wunschliste', to: 'home#wunschliste'
  get 'home/uberuns', to: 'home#uberuns'
  get 'home/kontakt', to: 'home#kontakt'
  get 'home/sonderwunsche', to: 'home#sonderwunsche'
  get 'home/agb', to: 'home#agb'
  get 'home/widerrufsrecht', to: 'home#widerrufsrecht'
  get 'home/versandkosten', to: 'home#versandkosten'
  get 'home/datenschutz', to: 'home#datenschutz', as: 'home_datenschutz'
  get 'home/impressum', to: 'home#impressum'
  get 'home/haarschumck', to: 'products#haarschumck'
  get 'home/patentspangenundmini-patenspangen', to: 'products#patentspangen_mini_patenspangen'
  get 'home/haarspange', to: 'home#haarspangen'
  get 'home/patentspange_aus_kunstharz_extil', to: 'products#patenspange_aus_kunstharz_textil'
  get 'home/haarreifen_aus_leder_nerz', to: 'products#haarreifen_haarbander'
  get 'home/curlys_haarnadeln', to: 'products#curlys_haarnadeln'
  get 'home/haarschieber_und_seitenspange', to: 'products#haarschieber_seitenspange'
  get 'home/haarkamme-haarklammern', to: 'products#haarkamme_haarklammern'
  get 'home/haargreifer-wellenreifen-strahnchenhalter', to: 'products#haargreifer_wellenreifen_strahnchenhalter'
  get 'home/zopfgummi_zopfruschen', to: 'products#zopfgummis_zopfruschen'
  get 'home/haarclips_magnetclips', to: 'products#haarclips_magnetclips'
  get 'home/klappspangen_zopfhalter', to: 'products#klappspangen_zopfhalter'
  get 'home/accessories', to: 'home#accessoires'
  get 'home/colliers_ketten-anhanger', to: 'products#colliers_ketten_anhanger', as: 'home_colliers_ketten_anhanger'
  get 'home/ringe', to: 'home#ringe'
  get 'home/ohrclips_ohrhaken_ohrringe_ohrstecker', to: 'products#ohrclips_ohrhaken_ohrringe_ohrstecker', as: 'home_ohrclips_ohrhaken_ohrringe_ohrstecker'
  get 'home/armbander_armring', to: 'products#armbander_armring'
  get 'home/broschen', to: 'products#broschen'
  get 'home/mode_brillen', to: 'products#mode_brillen', as: 'home_mode_brillen'
  get 'home/tasche_clutch', to: 'products#tasche_clutch', as: 'home_tasche_clutch'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def wunschliste
  end

  def meinkonto
  end

  def sonderwunsche
  end

  def kontakt
  end 

  def agb
  end

  def widerrufsrecht
  end

  def versandkosten
  end

  def datenschutz
  end

  def impressum
  end
  
  def haarschumck
  end

  def patentspangen_mini_patenspangen
  end

  def haarspangen
  end

  def patenspange_aus_kunstharz_textil
  end

  def haarreifen_haarbander
  end

  def haarreifen_diamen_metall
  end

  def haarreifen_aus_kunstoffharz_textil
  end

  def curlys_haarnadeln
  end

  def haarschieber_seitenspange
  end

  def haarkamme_haarklammern
  end

  def haargreifer_wellenreifen_strahnchenhalter
  end

  def zopfgummis_zopfruschen
  end

  def haarchips_magnetchips
  end

  def accessoires
  end

   def colliers_ketten_anhanger
  end

  def ringe
  end

  def ohrclips_ohrhaken_ohrringe_ohrstecker
  end

  def armbander_armring
  end

  def broschen
  end

  def mode_brillen
  end

  def tasche_clutch
  end
end

   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar bg-body-tertiary fixed-top">
  <div class="container-fluid">
    <%= image_tag 'vitaaurabalance-logo.jpg' %>
    <div class="d-flex align-items-center ms-auto me-3">
      <%= link_to "Wunschliste", home_wunschliste_path, class: "nav-link active me-2" %>
      <%= link_to"Über uns", home_uberuns_path, class: "nav-link active me-2" %>
      <%= link_to "Kontakt", home_kontakt_path, class: "nav-link active" %>
      <%= link_to "Sonderwünsche", home_sonderwunsche_path, class: "nav-link active me-2" %>
      <div class="d-flex align-items-center ms-auto">
        <ul class="navbar-nav d-flex flex-row align-items-center mb-2 mb-lg-0">
        <li class="nav-item me-3">
          <%= link_to '<i class="fas fa-search"></i>'.html_safe, '#', class: 'nav-link' %>
        </li>
        <li class="nav-item me-3">
          <%= link_to '<i class="fas fa-shopping-cart"></i>'.html_safe, '#', class: 'nav-link' %>
        </li>
        <li class="nav-item me-3">
          <%= link_to '<i class="fas fa-user"></i>'.html_safe, '#', class: 'nav-link' %>
        </li>
      </ul>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Home</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Haarschumck</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Patenspangen und Mini - Patentspangen
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Haarspange</a></li>
            <li><a class="dropdown-item" href="#">Patentspange aus Kunstharz & Textil</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown"> 
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Haarreifen und Haarbänder </a> 
          <ul class="dropdown-menu"> 
            <li><a class="dropdown-item" href="#">Haarreifen & Diamen aus Metall</a></li>
            <li><a class="dropdown-item" href="#">Haarreifen aus Kunstoffharz & Textil</a></li> 
            <li><a class="dropdown-item" href="#">Haargreifer / Wellenreifen und Strähnchenhalter</a></li> 
          </ul>
        </li>
        <li class="nav-item"> 
         <%= link_to 'Zopfgummis und Zopfrüschen', home_zopfgummi_zopfruschen_path, class: 'nav-link' %>
        </li> 
        <li class="nav-item"> 
          <a class="nav-link" href="#">Haarclips und Magneclips</a> 
            <%= link_to 'Zopfgummis und Zopfrüschen', home_zopfgummi_zopfruschen_path, class: 'nav-link' %>
        </li> 
        <li class="nav-item"> 
           <%= link_to 'Klappspangen und Zopfhalter', home_klappspangen_zopfhalter_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Accessories', home_accessories_path, class: 'nav-link' %> 
        </li> 
        <li class="nav-item"> 
          <li class="nav-item"> 
            <%= link_to 'Colliers, Ketten, Anhänge', home_colliers_ketten_anhanger_path, class: 'nav-link' %>  
          </li>
        </li>
        <li class="nav-item"> 
           <%= link_to 'Ringe', home_ringe_path, class: 'nav-link' %>   
        </li> 
        <li class="nav-item"> 
          <%= link_to 'Ohrclips, Ohrhaken, Ohrringe, Ohrstecker', home_ohrclips_ohrhaken_ohrringe_ohrstecker_path, class: 'nav-link' %> 
        </li> 
        <li class="nav-item">
           <%= link_to 'Armbänder, Armring', home_armbander_armring_path, class: 'nav-link' %>   
        </li> 
        <li class="nav-item">
         <%= link_to 'Broschen', home_broschen_path, class: 'nav-link' %>    
        </li> 
        <li class="nav-item"> 
           <%= link_to 'Mode, Brilllen', home_mode_brillen_path, class: 'nav-link' %> 
        </li> 
        <li class="nav-item"> 
            <%= link_to 'Tasche, Clutch', home_tasche_clutch_path, class: 'nav-link' %>
        </li> 
      </ul>
    </div> 
  </div> 
</nav>

app/views/home/agb.html.erb
<h1>AGB</h1>

<h4>Allgemeine Geschäftsbedingungen</h4>

<p>Vita-Aura-Balance</p>
<p> Frau Delia Curi<p>
<p>Auf'm Möhnert 9</p>
<p>59755 Arnberg<p>
<br/>

<p>Telefon: +49 2932 898883</p>
<p>WhatsApp: + 49 1633973826 *keine Anrufe, nur WhatsApp<p>
<p>Telefax: + 49 2932 941348</p>
<br/>

<p>E-mail-Adresse: info@vita-aura-balance.de</p>
<p> Ust-IdNr.: DE 223536033</p>
<br/>

<p>1. Geltungsbereich
Im Rahmen des Vita-Aura-Balance-Internet-Shops gelten die nachfolgenden Allgemeinen Geschäftsbedingungen (AGB) in der zum Zeitpunkt der Bestellung gültigen Fassung. Die AGB können von Ihnen für den Zweck der Online-Bestellung auf Ihrem Rechner abgespeichert und/oderausgedruckt werden.
</p>
<br/>

<p>2. Vertragsabschluss
(1) Alle unsere Angebote sind freibleibend.
(2) Ein Vertrag zwischen Vita-Aura-Balance und dem Besteller kommt durch die Annahme eines Angebots des Bestellers durch Vita-Aura-Balance zustande. Das Angebot des Bestellers erfolgt durch Übermittlung des vollständig ausgefüllten, durch Vita-Aura-Balance bereit gestellten Bestellformulars. Die Auftragsannahme durch die Firma Vita-Aura-Balance erfolgt durch Zusendung einer Bestätigung per E-Mail oder durch Lieferung der bestellten Ware. Das Angebot ist für den Besteller verbindlich, § 145 BGB. Vita-Aura-Balance ist nicht verpflichtet, Angebote des Bestellers anzunehmen und kann die Annahme jederzeit ohne Angabe von Gründen verweigern. In diesem Fall informiert Vita-Aura-Balance den Besteller unverzüglich über die Nichtannahme seines Auftrags per Email. Die Überprüfung der Bestätigung auf offensichtliche Schreib- und Rechenfehler sowie auf Abweichungen zwischen Bestellung, Bestätigung und Lieferung obliegt dem Bestellenden. Er ist weiterhin verpflichtet, eventuelle Unstimmigkeiten unverzüglich der Firma Vita-Aura-Balance mitzuteilen.</p>
<br/>

<p>3. Lieferung
(1) Die Firma Vita-Aura-Balance verpflichtet sich die bestellte Ware an die vom Kunden angegebene Adresse auszuliefern. Unser Geschenkservice bietet Ihnen außerdem an, das Paket an den Beschenkten und die Rechnung an den Besteller zu schicken.
(2) Für Lieferungen werden zusätzlich die jeweiligen auf der Website angegebenen Versandkosten in Rechnung gestellt.
(3) Lieferungen erfolgen in der Regel und ohne verbindliche Zusage innerhalb von fünf Werktagen (Lieferverzögerungen durch den Paketzusteller können wir leider nicht beeinflussen). Bei Vorauskasse richtet sich der Zeitpunkt der Versendung durch Vita-Aura-Balance und die Lieferzeit nach Ziffer 4.
(4) Sollten einmal nicht alle gewünschten Artikel auf Lager sein, sind Teillieferungen zulässig. Diese Nachlieferungen erfolgen portofrei. Sollte die von Ihnen bestellte Ware aufgrund nicht von Vita-Aura-Balance zu vertretender Umstände, insbesondere bei nicht rechtzeitiger Lieferung durch unsere Vertragspartner oder durch höhere Gewalt, bei uns nicht verfügbar sein, werden wir Sie darüber unverzüglich in Kenntnis setzen. Wir behalten uns in diesem Fall das Recht vor, uns vom Vertrag zu lösen und die bestellte Ware bei Nichtverfügbarkeit nicht zu liefern. Sollten Sie den Kaufpreis bereits entrichtet haben, so werden wir diesen selbstverständlich unverzüglich erstatten.
(5) Sie helfen uns, wenn Sie bei der Übernahme unserer Lieferungen durch das Transportunternehmen darauf achten, dass die Pakete weder geöffnet, beschädigt noch in sonstiger Weise manipuliert wurden. Ist dies dennoch der Fall, bitten wir Sie höflich, dies auf dem Übergabeprotokoll des Lieferanten des Transportunternehmens schriftlich festzuhalten. Sollten Sie eine vorherige Öffnung, Beschädigung oder sonstige
Manipulation Ihres Pakets erst nach der Übergabe feststellen, bitten wir Sie ebenfalls höflich, dies unverzüglich bei dem betreffenden Transportunternehmen zu reklamieren. Ihre gesetzlichen Ansprüche bleiben jedoch auch erhalten, wenn Sie diese Reklamation gegenüber dem Transportunternehmen nicht durchführen.</p>

<p>4. Widerrufsbelehrung - Widerrufsrecht und Rücksendung der Ware
(1) Wenn der Käufer ein Unternehmer (vgl. Ziffer 1.2 unserer AGB) im Sinne des § 14 Bürgerlichen Gesetzbuches (BGB) ist, besteht kein Widerrufsrecht.
(2) Für Verbraucher (jede natürliche Person ist, die ein Rechtsgeschäft zu einem Zwecke abschließt, der weder ihrer gewerblichen noch ihrer selbständigen beruflichen Tätigkeit zugerechnet werden kann) gilt:Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses. Um Ihr Widerrufsrecht auszuüben, müssen Sie uns Firma Vita-Aura-Balance, Auf´m Möhnert 9, 59755 Arnsberg, Email: info@vita-aura-balance.de. mittels einer eindeutigen Erklärung (z.B. ein mit der Post versandter Brief, Telefax oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.
Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet. Haben Sie verlangt, dass die Dienstleistungen während der Widerrufsfrist beginnen soll, so haben Sie uns einen angemessenen Betrag zu zahlen, der dem Anteil der bis zu dem Zeitpunkt, zu dem Sie uns von der Ausübung des Widerrufsrechts hinsichtlich dieses Vertrags unterrichten, bereits erbrachten Dienstleistungen im Vergleich zum Gesamtumfang der im Vertrag vorgesehenen Dienstleistungen entspricht.
(3) Die Kosten des Rückversandes trägt grundsätzlich der Kunde.
(4) Ausschluss des Widerrufsrechtes
Das Widerrufsrecht besteht im Sinne § 312d IV BGB unter anderem nicht bei Fernabsatzverträgen zur Lieferung von Waren, die nach Kundenspezifikation angefertigt werden oder eindeutig auf die persönlichen Bedürfnisse zugeschnitten sind, oder die aufgrund ihrer Beschaffenheit nicht für eine Rücksendung geeignet sind oder schnell verderben können oder deren Verfalldatum durch die Rücksendung überschritten würde.</p>
<br/>

<p>5. Zahlungsbedingungen und Versandkosten
(1) Die im Internet genannten Preise enthalten die gesetzliche Mehrwertsteuer Deutschlands und gelten bis zum Erscheinen einer neuen Preisliste.
Für unsere Schweizer Kunden wird am Ende der Bestellung die Mehrwertsteuer abgegolten. Preiserhöhungen nach Vertragsabschluss sind ausgeschlossen.
(2) Innerhalb Deutschlands beträgt der Mindestbestellwert 30,00 €.
Der Mindestbestellwert für EU-Länder beträgt 70,00 €.
Wir erheben innerhalb Deutschlands eine Versandkostenpauschale von 5,50 € pro Bestellung.
Für die Lieferung in EU-Länder außerhalb Deutschlands fällt immer eine Porto-Pauschale in Höhe von 19,99 € an.
Für die Lieferung ins Nicht-EU-Ausland (Schweiz, ...) fällt immer eine Porto-Pauschale in Höhe von 24,99 € an.
(3) Die Zahlung erfolgt durch eine auf dem Online-Bestellformular angebotene Zahlungsweise, d.h. Via Pay Pal oder per Vorauskasse (Überweisung). Wir behalten uns vor, aus technischen Gründen einzelne Zahlungsarten zeitweise abzuschalten. Bitte beachten Sie, dass bei Zahlungen durch Vorkasse der Warenversand erst durchgeführt werden kann, wenn die Bezahlung auf dem Konto der Firma Vita-Aura-Balance
eingegangen ist.</p>
<br/>

<p>6. Eigentumsvorbehalt
Bis zur vollständigen Bezahlung bleibt die Ware unser Eigentum.</p>
</br/>

<p>7. Mängelansprüche und Haftung
(1) Es gelten die gesetzlichen Mängelgewährleistungsrechte.
(2) Für Mängelrügen durch Kaufleute gelten die gesetzlichen Bestimmungen des Handelsgesetzbuches.
(3) Der Käufer ist verpflichtet, dem Verkäufer die mangelhafte Ware zuzusenden.
(4) Keine Gewährleistungspflicht besteht für Schäden durch normale Abnutzung sowie unsachgemäße Handhabung. Bei Rücksendung zu Recht beanstandeter Ware trägt der Verkäufer die Transportgefahr sowie die Kosten der Rücksendung. Die erneute Zustellung der Ware erfolgt ebenfalls auf Gefahr und Kosten des Verkäufers. Es gelten die oben genannten Lieferbedingungen.
(5) Wir haften ausschließlich für verschuldete Schäden bei der Verletzung wesentlicher vertraglicher Hauptpflichten (Kardinalpflichten) soweit die Haftung nicht nach § 8 (6) besteht. Eine weitergehende Haftung ergibt sich nur aus dem Produkthaftungsgesetz oder durch vorsätzliches oder grob fahrlässiges Verhalten durch den Verkäufer bzw. dessen Erfüllungsgehilfen.
(6) Eine gesetzlich vorgeschriebene verschuldensunabhängige Haftung von Vita-Aura-Balance bleibt von den vorstehenden Haftungseinschränkungen unberührt. Gleiches gilt bei schuldhafter Verletzung von Leben, Körper oder Gesundheit sowie bei Geltendmachung von Ansprüchen nach §§ 1, 4 Produkthaftungsgesetz.</p>
<br/>

<p>8. Anwendbares Recht
Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts (CISG). Gerichtsstand ist soweit der Käufer einer Gerichtsstandvereinbarung zugänglich ist, das Gericht am Sitz des Verkäufers.</p>
<br/>

<p>9. Online-Streitbeilegung gemäß Art. 14 Abs. 1 ODR-VO: Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit. Die Plattform finden Sie unter http://ec.europa.eu/consumers/odr/ - unsere e-Mail-Adresse: info@vita-aura-balance.de</p>
<br/>

<p>10. Datenschutz
Personenbezogene Daten werden vertraulich behandelt und ausschließlich im Rahmen der geltenden Datenschutzgesetze genutzt und verarbeitet.</p>
<br/>

<p>Widerrufsformular</p>
<br/>
 es zurück.)
<p>(Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie  es zurück.)</p>
<br/>

<p>An :</p>
<p>Fima Vita-Aura-Balance</p>
<p>Auf'm Möhnrt 9</p>
<p>59755<p>
<p>Email: info@vita-aura-balance.de</p>
<br/>


<p>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*)/die Erbringung der folgenden Dienstleistung (*):</p>
<br/>

<p>Bestellt am (*)/erhalten am (*): __________________________________________ </p>
<br/>

<p>Name des/der Verbraucher(s): _________________________________________<p>
	<br/>

<p>Anschrift: ________________________________________________________________________</p>

app/views/home/index.html.erb
<div id="carouselExampleSlideOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="catousel-item active">
            <%=image_tag "Slide1", class: 'd-block w-100', alt: "Slide1" %>
        </div>
        <div class="carousel-item">
            <%= image_tag "Slide2", class: 'd-block w-100', alt:"Slide2" %>
        </div>
        <div class="carousel-item">
            <%= image_tag "Slide3", class: 'd-block w-100', alt: "Slide3" %>
        </div>
    </div>
</div>

app/views/home/kontakt.html.erb
<h1>Kontakt</h1>
<br/>
<br/>

<p>Um uns eine Nachricht zu schicken, füllen Sie einfach all mit *markierten Felder aus und klicken Sie auf "Abschicken".</p>

app/views/home/sonderwunsche.html.erb
<h3>Sonderwünsche</h3>

<p>Haben Sie besondere Wünsche wie z.B. einen Farbwunsch, versuchen wir diesen, nach Absprache mit Ihnen, umzusetzen. Da dieses Spezialanfertigungen sind, können wir diese Produkte leider nicht zurücknehmen.</p>

app/views/home/uberuns.html.erb
<h3>Unsere Geschichte: Von der Leidenschaft zum
Haarschmuck-Paradies</h3>

<p>Haarschmuck ist für mich mehr als nur ein Accessoire – er ist
Ausdruck von Persönlichkeit und Stil. Als leidenschaftliche
Trägerin habe ich selbst oft nach einzigartigen Stücken gesucht,
die sich von der Masse abheben. Doch die Suche nach
hochwertigen und individuellen Designs gestaltete sich oft
schwierig.</p>
<br>
<p>Aus dieser Sehnsucht heraus entstand die Idee für meinen
eigenen Online-Shop. Ende 2008 eröffnete ich mein kleines
Haarschmuck-Paradies, das sich mittlerweile zu einer
Gemeinschaft von gleichgesinnten Schmuckliebhaberinnen
entwickelt hat. Meine treuen Kundinnen, mit denen ich oft per
WhatsApp in Kontakt stehe, teilen meine Leidenschaft für
besondere Accessoires.</p>
<br>
<p>Einzigartige Designs für besondere Persönlichkeiten
In meinem Shop finden Sie handgefertigten Haarschmuck in
limitierter Auflage, der sich durch Qualität und Individualität
auszeichnet. Ob Vintage-Charme, moderne Eleganz oder
verspielter Retro-Stil – meine Kollektionen, die zweimal jährlich
aktualisiert werden, bieten für jeden Geschmack das passende
Schmuckstück.</p>
<br>
<p>Jedes meiner Kunstwerke wird mit viel Liebe zum Detail aus
hochwertigen Materialien wie Kunststoff, Stoff, Metall, Leder und
mehr gefertigt. Dabei lege ich großen Wert auf faire
Produktionsbedingungen, sowohl in Deutschland als auch im
Ausland.</p>
<br>
<p>Haarschmuck als Ausdruck von Stil und Individualität
Meine Kundinnen sind Frauen, die Wert auf Qualität und
Individualität legen und ihren eigenen Stil mit besonderen
Accessoires unterstreichen möchten. Mein Ziel ist es, Ihnen ein
Gefühl von Selbstbewusstsein und Freude zu schenken, wenn Sie
meine einzigartigen Stücke tragen.</p>
</br>
<p>Ein Hauch von Peru in Deutschland
Hinter diesem Shop stehe ich, eine Peruanerin mit über 40 Jahren
Erfahrung in Deutschland. Meine beiden Heimaten, Peru und
Deutschland, prägen meine Leidenschaft für Haarschmuck und
meine Liebe zum Leben. Neben dem Schmuck liebe ich Lesen,
Tanzen, Sport, Meditation und gutes Essen.
Lassen Sie sich von meinem Haarschmuck inspirieren und
unterstreichen Sie Ihre einzigartige Schönheit. Ich glaube daran,
dass jede Frau strahlen kann – mit dem richtigen Accessoire.</p>
</p>
</br>
<p>Mit funkelnden Grüßen,</p>
</br>
<p>Delia</p>

app/views/layouts/_footer_navbar.html.erb
<nav  class="navbar navbar-expand-lg navbar-light bg-light fixed-bottom">
<div class="container">
	<a class="navbar-brand" href="#"></a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#footerNavbar" aria-controls="footerNavbar" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="footerNavbar">
		<ul class="navbar-nav ms-auto">
			<li class="nav-item">
				<%= link_to 'Home', home_root_path, class:'nav-link' %>
			</li>
			<li class="nav-item">
				<%= link_to 'AGB', home_agb_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to 'Widerrufsrecht', home_widerrufsrecht_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to 'Datenschutz', home_datenschutz_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to 'Versandkosten & Zahlungsarten', home_versandkosten_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to 'Impressum', home_impressum_path, class: "nav-link" %>
			</li>
		</ul>
	</div>
</div>
</nav>

<footer>
&copy;2024 Vita Aura Balance
</footer>